# -*- coding: utf-8 -*-
"""areas_of_shapes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VSfaHLNGxjJbclIfkWrA_Ig4ZWqT6X4U
"""

import math

def area(shape, **kwargs):
    """
    Calculate area for different shapes.
    shape: 'circle', 'rectangle', or 'triangle'
    kwargs:
      - circle: radius
      - rectangle: length, width
      - triangle: base, height
    """
    shape = shape.lower()
    if shape == 'circle':
        r = kwargs.get('radius', 0)
        return math.pi * r * r
    elif shape == 'rectangle':
        l = kwargs.get('length', 0)
        w = kwargs.get('width', 0)
        return l * w
    elif shape == 'triangle':
        b = kwargs.get('base', 0)
        h = kwargs.get('height', 0)
        return 0.5 * b * h
    else:
        raise ValueError("Unsupported shape: choose 'circle', 'rectangle', or 'triangle'")

# Example calls
print("Circle, r=3 ->", area('circle', radius=3))        # expected ≈ 28.2743
print("Rectangle, 4x5 ->", area('rectangle', length=4, width=5))  # expected 20
print("Triangle, b=6 h=4 ->", area('triangle', base=6, height=4)) # expected 12

