# -*- coding: utf-8 -*-
"""csv(colab).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rjx3iTjsHwKctUlny3K_XvMgSMidLdGC
"""

import pandas as pd
import os

# Function to analyze CSV
def analyze_csv(file_path):
  """
  Reads a CSV file and calculates the mean, minimum, and maximum of each numeric column.

  Args:
    file_path (str): The path to the CSV file.

  Returns:
    pandas.DataFrame: A DataFrame containing the mean, minimum, and maximum
                      for each numeric column.
  """
  try:
    df = pd.read_csv(file_path)
  except FileNotFoundError:
    print(f"Error: File not found at {file_path}")
    return None

  numeric_cols = df.select_dtypes(include=['number'])

  if numeric_cols.empty:
    print("No numeric columns found in the CSV file.")
    return None

  analysis_results = numeric_cols.agg(['mean', 'min', 'max'])

  return analysis_results

# Create a sample DataFrame and save to CSV
data = {'col1': [1, 2, 3, 4, 5],
        'col2': [10, 20, 30, 40, 50],
        'col3': ['A', 'B', 'C', 'D', 'E']}
sample_df = pd.DataFrame(data)
sample_csv_path = 'sample_data.csv'
sample_df.to_csv(sample_csv_path, index=False)
print(f"Sample CSV file created at: {sample_csv_path}")

# Example usage with the sample CSV file
file_path = 'sample_data.csv'
analysis_output = analyze_csv(file_path)

if analysis_output is not None:
  print("Analysis Results:")
  display(analysis_output)

