# -*- coding: utf-8 -*-
"""palindrome(colab).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xEJDRyZ7SSkCj1Wq1NiFBL49GDFsNhLC
"""

import re

def is_palindrome(text):
    """
    Checks if a string is a palindrome, ignoring case, spaces, and punctuation.

    Args:
        text: The input string.

    Returns:
        True if the string is a palindrome, False otherwise.
    """
    # Convert to lowercase and remove non-alphanumeric characters
    processed_text = re.sub(r'[^a-zA-Z0-9]', '', text).lower()

    # Check if the processed string is equal to its reverse
    return processed_text == processed_text[::-1]

# Example usage
print(is_palindrome("A man, a plan, a canal: Panama"))
print(is_palindrome("racecar"))
print(is_palindrome("hello world"))